### ISSUE TITLE
UITest.com

### ISSUE THREAD

**Issue by j9t** [simevidas/web-dev-feeds#16]
If this fits the profile for your selection, I’m suggesting https://uitest.com/ (and the corresponding feed, https://uitest.com/feed/)—the site features web development tools on a usually weekly basis.

(Disclosure: I run this site—thanks for including meiert.com, by the way!)

**Comment by simevidas** [comment]
👍 I’ve subscribed in my RSS reader. It will be added to this repo in the next monthly update.

**Comment by j9t** [comment]
Awesome 🙏
