### ISSUE TITLE
lihautan.com

### ISSUE THREAD

**Issue by simevidas** [simevidas/web-dev-feeds#21]
Blog URL: https://lihautan.com/blogs/

---

Twitter discussion: https://twitter.com/simevidas/status/1302603063786692608

**Comment by tanhauhau** [comment]
the rss feed is available here now: https://lihautan.com/rss.xml

**Comment by simevidas** [comment]
Thanks!

It seems that there a few validity issues: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flihautan.com%2Frss.xml

<img width="844" alt="Screen Shot 2020-09-07 at 9 57 16 PM" src="https://user-images.githubusercontent.com/716405/92414634-6196ac00-f155-11ea-9f57-61df2c7ee9f4.png">

I checked because Feedly says the feed is unreachable:

<img width="827" alt="Screen Shot 2020-09-07 at 9 59 33 PM" src="https://user-images.githubusercontent.com/716405/92414655-7a9f5d00-f155-11ea-9210-f6adbaeb7dae.png">

“Unreachable” seems to be Feedly’s catch-all error. I don’t really know what it means exactly, but it’s possible that fixing those validity errors will fix the issue in Feedly.

Regarding the “invalid character” errors, I think the validator complains about un-escaped spaces in the URL.

**Comment by simevidas** [comment]
The feed now works correctly in Feedly and is no longer unreachable. 👍
