### ISSUE TITLE
blog.innerht.ml

### ISSUE THREAD

**Issue by simevidas** [simevidas/web-dev-feeds#44]
https://blog.innerht.ml/

<img width="608" alt="Screen Shot 2021-06-25 at 12 27 54 AM" src="https://user-images.githubusercontent.com/716405/123340257-3a766300-d54c-11eb-82be-5b3cfb2c605d.png">

**Comment by simevidas** [comment]
Site is back up.

**Comment by sharat789** [comment]
Site is back down.

<img width="675" height="224" alt="Image" src="https://github.com/user-attachments/assets/7b9b1501-a872-4543-9186-4a5689ccac16" />
