### ISSUE TITLE
Add “Magazines” category?

### ISSUE THREAD

**Issue by j9t** [simevidas/web-dev-feeds#50]
Online publications like A List Apart, Smashing Magazine, and others are currently filed under “People,” but this is a bit confusing. (“People” sounds more like individuals than groups of people.)

How about a category “Magazines” or “Publications” that allows quick access to publications, limiting “People” to individuals?

**Comment by simevidas** [comment]
That’s a good idea! “Magazines” sounds neat. I’ll start slowly moving feeds to this category as I encounter new articles.

**Comment by simevidas** [comment]
Magazines category added https://github.com/simevidas/web-dev-feeds/blob/master/feeds.opml#L220-L227
