### ISSUE TITLE
Combined feed

### ISSUE THREAD

**Issue by Jak2k** [simevidas/web-dev-feeds#58]
This is to much for my poor feed reader.

Would it possible to offer a combined feed containing all the latest from all the feeds?

**Comment by simevidas** [comment]
What you’re asking sounds like the exact thing that a feed reader does. Try the Feedbro browser extension. It performs very well. It will take a day or two to fetch all the feeds, but after that it will start showing you only the latest feed items.

**Comment by Jak2k** [comment]
How long does it take to update the feeds?

**Comment by simevidas** [comment]
As a browser extension, Feedbro is constantly updating the feeds in the background. I haven’t noticed any significant delays. The Feedbro icon in my browser’s toolbar shows a badge with the number of new unread items.

**Comment by Jak2k** [comment]
I now set up FreshRSS on my server. I added the OPML as dynamic OPML. It now fetched it and loads all feeds.
